# Generated by Django 2.0.7 on 2018-07-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180729_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='topping',
        ),
        migrations.AddField(
            model_name='sub',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='sub_topping', to='orders.Topping'),
        ),
    ]
