# Generated by Django 2.0.7 on 2018-07-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180729_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dinplat',
            field=models.ManyToManyField(blank=True, related_name='cart', to='orders.Dinplat'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='cart', to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='saladpast',
            field=models.ManyToManyField(blank=True, related_name='cart', to='orders.SaladPasta'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sub',
            field=models.ManyToManyField(blank=True, related_name='cart', to='orders.Sub'),
        ),
    ]
