# Generated by Django 2.0.7 on 2018-07-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180730_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='dinplat',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='saladpast',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sub',
        ),
        migrations.AddField(
            model_name='dinplat',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='dinplat', to='orders.Cart'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='pizza', to='orders.Cart'),
        ),
        migrations.AddField(
            model_name='saladpasta',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='saladpasta', to='orders.Cart'),
        ),
        migrations.AddField(
            model_name='sub',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='sub', to='orders.Cart'),
        ),
    ]
