# Generated by Django 2.0.7 on 2018-08-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180801_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pizza_topping',
            field=models.TextField(blank=True, null=True),
        ),
    ]
