# Generated by Django 2.0.7 on 2018-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_pizza_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pizza_topping',
        ),
        migrations.AddField(
            model_name='cart',
            name='pizza_topping',
            field=models.ManyToManyField(blank=True, related_name='cart_topping', to='orders.Topping'),
        ),
    ]
