# Generated by Django 2.0.7 on 2018-08-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180802_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
