# Generated by Django 2.0.7 on 2018-08-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180802_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_size', to='orders.Size'),
        ),
    ]
