# Generated by Django 2.0.7 on 2018-08-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180802_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pizza_topping',
        ),
    ]
