# Generated by Django 2.0.7 on 2018-08-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_cart_pizza_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinplatname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='dinplat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinplatname', to='orders.Dinplatname'),
        ),
        migrations.AlterField(
            model_name='dinplat',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
