# Generated by Django 2.0.7 on 2018-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180802_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='sub',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='subtopping', to='orders.Subtopping'),
        ),
    ]
